apiVersion: v1
kind: Template
metadata:
   name: template-user10
parameters:
- name: APPLICATION_NAME
  displayName: Application's Name
  description: How you want to call your application's name
  required: true
  value: app-user10
- name: orizon-defb
  displayName:  orizon-defb's Name
  description: orizon-defb for Test Drive Access
  required: true
  value: orizon-defb
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
	name: ${APPLICATION_NAME}
	labels:
  	name: ${APPLICATION_NAME}
  spec:
	replicas: 1
	selector:
  	app: ${APPLICATION_NAME}
  	deploymentconfig: ${APPLICATION_NAME}
	template:
  	metadata:
    	labels:
      	app: ${APPLICATION_NAME}
      	deploymentconfig: ${APPLICATION_NAME}
  	spec:
    	containers:
    	- image: jboss/wildfly:latest
      	name: ${APPLICATION_NAME}
      	ports:
      	- containerPort: 8080
        	protocol: TCP
- apiVersion: v1
  kind: Service
  metadata:
	labels:
  	name: ${APPLICATION_NAME}
	name: ${APPLICATION_NAME}
  spec:
	ports:
	- port: 8080
  	protocol: TCP
  	targetPort: 8080
	selector:
  	app: ${APPLICATION_NAME}
  	deploymentconfig: ${APPLICATION_NAME}
	sessionAffinity: None
	type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
	labels:
  	name: ${APPLICATION_NAME}
	name: ${APPLICATION_NAME}
  spec:
	host: ${APPLICATION_NAME}.apps.orizon-defb.open.redhat.com
	port:
  	targetPort: 8080
	to:
  	kind: Service
  	name: ${APPLICATION_NAME}
  	weight: 100
